#!/usr/bin/env node

const Path = require('path');
const Fs = require('fs');

const _ = require('lodash');

const SERVICE_METADATA_ACTION = process.env.SERVICE_METADATA_ACTION || 'UPDATE';
const SERVICES_METADATA_FILE = Path.resolve(__dirname, '../services.json');

const {
    SERVICE_NAME,
    SERVICE_METADATA
} = process.env;

const servicesMetadata = JSON.parse(Fs.readFileSync(SERVICES_METADATA_FILE, 'utf8'));
const serviceMetadata  = JSON.parse(Buffer.from(SERVICE_METADATA, 'base64').toString('utf-8'));

if (SERVICE_METADATA_ACTION === 'UPDATE') {
    if (!servicesMetadata[SERVICE_NAME]) {
        servicesMetadata[SERVICE_NAME] = serviceMetadata;
    } else {
        _.merge(servicesMetadata[SERVICE_NAME], serviceMetadata);
    }   
} else if (SERVICE_METADATA_ACTION === 'DELETE') {
    _.unset(servicesMetadata, `${SERVICE_NAME}.${serviceMetadata}`);
}

const updatedServiceMetadata = JSON.stringify(servicesMetadata, null, 2);

Fs.writeFileSync(SERVICES_METADATA_FILE, updatedServiceMetadata);

console.log(updatedServiceMetadata);
